# worker/wrangler.toml
name = "spotify-now-playing"
main = "src/index.js"
compatibility_date = "2025-04-11"

[[kv_namespaces]]
binding = "TOKEN_CACHE"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[vars]          # <- safe, non‑secret
CLIENT_ID = "540b1cf18a9a4e5383fd2d5a6a287d80"
