name = "spotify-now-playing"
main = "worker/index.js"
compatibility_date = "2024-04-10"

[vars]
CLIENT_ID = "your_spotify_client_id"
CLIENT_SECRET = "your_spotify_client_secret"
REFRESH_TOKEN = "your_refresh_token"
ACCESS_TOKEN = ""
EXPIRES_AT = 0
